apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: elder-kettle
  labels:
    app: elder-kettle
    release: kp
spec:
  selector:
    matchLabels:
      app: elder-kettle
  podMetricsEndpoints:
  - interval: 15s
